spring:
  profiles:
    group:
      physical-threads: thread-pool
      virtual-threads: thread-pool

glue:
  window:
    height: 1030
    width: 1700
  board:
    rows: 320
    columns: 840
    font-size: 2
  calculation:
    board-delay: 0
    cell-delay: 0
