# TODO - add profiles:
#  - calculate in a single thread
#  - calculate with a pool of threads
#  - calculate with a pool of virtual threads
glue:
  window:
    height: 1030
    width: 1700
  board:
    rows: 320
    columns: 840
    font-size: 2
  calculation:
    board-delay: 0
    cell-delay: 0